### PR TITLE
Fix DateTimeParseException in FHIR import

### LINKED ISSUE #18: DateTimeParseException when `StructureDefinition.date` is a `YYYY-MM-DD`
e.g. import https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-AllergyIntolerance-1

```xml
<StructureDefinition xmlns="http://hl7.org/fhir">
   <id value="CareConnect-GPC-AllergyIntolerance-1"></id>
   <meta>
      <lastUpdated value="2018-08-02T12:07:36.924+01:00"></lastUpdated>
   </meta>
   <text>
      <status value="generated"></status>
   </text>
   <extension url="http://hl7.org/fhir/StructureDefinition/structuredefinition-wg">
      <valueCode value="pc"></valueCode>
   </extension>
   <url value="https://fhir.nhs.uk/STU3/StructureDefinition/CareConnect-GPC-AllergyIntolerance-1"></url>
   <version value="1.7.0"></version>
   <name value="CareConnect-GPC-AllergyIntolerance-1"></name>
   <status value="active"></status>
   <date value="2020-02-17"></date><!-- YYYY-MM-DD -->
   <publisher value="HL7 UK"></publisher> <snip/>
```

`OffsetDateTime` expects a time, but `FHIR::dateTime` allows it to be omitted.

## Server Error

We're sorry, but the server responded with an error message.

## Details

```json
{
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null
  },
  "status": 500,
  "statusText": "OK",
  "url": "http://localhost:8082/api/dataModels/import/uk.ac.ox.softeng.maurodatamapper.plugins.fhir.datamodel/FhirDataModelImporterProviderService/2.2.0",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for http://localhost:8082/api/dataModels/import/uk.ac.ox.softeng.maurodatamapper.plugins.fhir.datamodel/FhirDataModelImporterProviderService/2.2.0: 500 OK",
  "error": {
    "status": 500,
    "reason": "Internal Server Error",
    "errorCode": "UEX--",
    "message": "Text '2020-02-17' could not be parsed at index 10",
    "path": "/api/dataModels/import/uk.ac.ox.softeng.maurodatamapper.plugins.fhir.datamodel/FhirDataModelImporterProviderService/2.2.0",
    "version": "5.2.0",
    "exception": {
      "type": "DateTimeParseException",
      "message": "Text '2020-02-17' could not be parsed at index 10",
      "stacktrace": [
        "uk.ac.ox.softeng.maurodatamapper.plugins.fhir.ImportDataHandling$Trait$Helper.updateFhirImportedModelFromParameters(ImportDataHandling.groovy:64)",
        "uk.ac.ox.softeng.maurodatamapper.plugins.fhir.datamodel.provider.importer.FhirDataModelImporterProviderService.updateImportedModelFromParameters(FhirDataModelImporterProviderService.groovy:84)",
        "uk.ac.ox.softeng.maurodatamapper.core.provider.importer.ModelImporterProviderService$_importDomains_closure1.doCall(ModelImporterProviderService.groovy:56)",
        "uk.ac.ox.softeng.maurodatamapper.core.provider.importer.ModelImporterProviderService.importDomains(ModelImporterProviderService.groovy:55)",
        "uk.ac.ox.softeng.maurodatamapper.core.importer.ImporterService.importDomains(ImporterService.groovy:66)",
        "uk.ac.ox.softeng.maurodatamapper.core.controller.ModelController.$tt__importModels(ModelController.groovy:713)",
        "grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)",
        "org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)",
        "grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)",
        "org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223)",
        "org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)",
        "org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)",
        "org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)",
        "org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)",
        "org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)",
        "org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)",
        "org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)",
        "org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)",
        "org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)",
        "org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:126)",
        "org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:64)",
        "org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:101)",
        "org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:119)"
      ]
    }
  }
}
```

### PR DESCRIPTION
**Pull request by awilkins**
fixes #18

### CODE REVIEW

**Comment by joe-crawford** [comment]
Hi @awilkins, many thanks for the contribution!

I'm looking at the `date` format for FHIR (https://build.fhir.org/datatypes.html#date) and wondering if there might be an issue if only the year or year and month are provided? 

I think it may be possible to do this with the `OffsetDateTime.parse(date, <format>)` where <format> is something like `YYYY[-MM[-DD]]`, which would avoid the string manipulation.

File: src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/plugins/fhir/datamodel/provider/importer/FhirDataModelImporterProviderServiceSpec.groovy [hunk 1]
```diff
@@ -502,6 +502,7 @@ class FhirDataModelImporterProviderServiceSpec extends BaseIntegrationSpec {
         assert dataModel.label == entryId
         dataModel.folder = folder
         dataModelService.validate(dataModel)
+        fhirDataModelImporterProviderService.updateImportedModelFromParameters(dataModel, parameters, false)
```
Comment (joe-crawford) [inline src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/plugins/fhir/datamodel/provider/importer/FhirDataModelImporterProviderServiceSpec.groovy:505]: Just FYI I think this should already be called through the parent class ModelImporterProviderService (in `importDomain`).

Comment (awilkins) [reply src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/plugins/fhir/datamodel/provider/importer/FhirDataModelImporterProviderServiceSpec.groovy:505]: Added this line on the basis that the current tests should fall foul of the parsing error (because they use data harvested from the same source, with the same format in the `date` field), but don't.

A breakpoint placed inside the `updateImportedModelFromParameter` method does not trip when debugging the tests in `FhirDataModelImporterProviderServiceSpec`.

- Placed a `throw IllegalArgumentException("date parse")` just before the date parse so all calls will fail
- This results in 9 failures, none of them for importing `StructureDefinition` (all code sets and terminologies)

Comment (joe-crawford) [reply src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/plugins/fhir/datamodel/provider/importer/FhirDataModelImporterProviderServiceSpec.groovy:505]: @awilkins, sorry, I had not noticed that this was in the `Spec` file not the actual importer! Yes I agree that makes sense in the tests :)

**Comment by awilkins** [comment]
Had a crack with various permutations of `DateTimeFormatter`

- Found it very hard to construct a custom format string that matches ISO8601
    - The `X` token is the closest for zone but includes whitespace and a colon
    - The code that actually builds the ISO formats in `DateTimeFormatter` uses inner classes of `DateTimeFormatterBuilder`
- `.ISO_LOCAL_DATE` doesn't work because `OffsetDateTime.parse()` demands a zone offset
- `.ISO_OFFSET_DATE` doesn't work because `OffsetDateTime.parse()` needs the `InstantSeconds` field which this doesn't set
- `.ISO_OFFSET_DATE_TIME` (the default) which does set zone and `InstantSeconds` requires the time and zone string

Even if we had a parser with optional bits missing, I think that `OffsetDateTime` is going to want them to not be missing.

Changing the type of `dateFinalised` in the `VersionAware` trait would probably be quite disruptive, so I'm content with it in it's current state.

**Comment by joe-crawford** [comment]
OK, thanks for that, yes I agree changing the format in VersionAware would have a big impact. I'll merge this PR.

**Comment by awilkins** [comment]
Any chance of a 5.2.1 release? Getting this fix into an instance is mildly fiddly without it.

**Comment by jamesrwelch** [comment]
@awilkins We've been building up to our 2023.1 release of all core, ui, and major plugins, and we'll hopefully be doing that in the next week or so
